package com.skillcentric

// Without data class
class Client(val name: String, val postalCode: Int) {

    // Overriding toString() method
    override fun toString(): String {
        return "Client(name = $name, postalCode = $postalCode"
    }

    // Overriding equal() method
    // In kotlin == and .equal() are the same
    override fun equals(other: Any?): Boolean {

        if (other == null || other !is Client)
            return false

        return name == other.name &&
                postalCode == other.postalCode
    }

    // Always override hashCode() with equals()
    override fun hashCode(): Int = name.hashCode() + 31 * postalCode

    // copy() method is also generated by the compiler in data classes
    fun copy(name: String = this.name,
             postalCode: Int = this.postalCode) = Client(name, postalCode)
}

// Data class demo
data class ImprovedClient(val name: String, val postalCode: Int)

fun main(args: Array<String>) {


}

